DROP TABLE SC;

DROP TABLE S;

DROP TABLE C;

-- 1．建立教学数据库的三个基本表（表创建时需添加PK、FK约束cascade on delete）：
-- S(Sno,Sname,Sgender,Sage,Sdept)   学生（学号，姓名，性别，年龄，系） 
-- SC(Sno,Cno,Grade)              选课（学号，课程号，成绩）
-- C(Cno,Cname,Cpno,Ccredit)      课程（课程号，课程名，先行课，学分）

CREATE TABLE S (
    SNO INT,
    SNAME VARCHAR(10),
    SGENDER VARCHAR(2),
    SAGE INT,
    SDEPT VARCHAR(10),
    CONSTRAINT PK_S PRIMARY KEY(SNO)
);

CREATE TABLE C (
    CNO INT,
    CNAME CHAR(10),
    CPNO INT,
    CCREDIT INT,
    CONSTRAINT PK_C PRIMARY KEY(CNO)
);

CREATE TABLE SC (
    SNO INT CONSTRAINT FK_SNO REFERENCES S(SNO) ON DELETE CASCADE,
    CNO INT CONSTRAINT FK_CNO REFERENCES C(CNO) ON DELETE CASCADE,
    GRADE INT,
    CONSTRAINT PK_SC PRIMARY KEY (SNO, CNO)
);

-- 2．建表后，为Sname添加Not NULL约束、Grade添加>0约束、Cname添加 Unique约束。
ALTER TABLE S MODIFY SNAME CONSTRAINT SNAME_NOT_NULL NOT NULL;
ALTER TABLE SC ADD CONSTRAINT GRADE_POSITIVE CHECK (GRADE>0);
ALTER TABLE C ADD CONSTRAINT CNAME_UNIQUE UNIQUE (CNAME);

-- 查看表的约束
SELECT TABLE_NAME,CONSTRAINT_NAME
FROM all_constraints
WHERE table_name IN ('C','SC','S')
ORDER BY TABLE_NAME;

-- 插入数据
INSERT ALL 
INTO S VALUES (121,'张三','F',17,'CS') 
INTO S VALUES (122,'李四','M',19,'MATH') 
INTO S VALUES (123,'张五','M',21,'PHY')
SELECT 1 FROM DUAL;

INSERT ALL 
INTO C VALUES (1,'DB',2,3)
INTO C VALUES (2,'OS',3,3)
INTO C VALUES (3,'C',NULL,3)
INTO C VALUES (4,'JAVA',3,2)
SELECT 1 FROM DUAL;

INSERT ALL 
INTO SC VALUES (121,1,59)
INTO SC VALUES (121,2,80)
INTO SC VALUES (122,1,95)
INTO SC VALUES (122,2,90)
INTO SC VALUES (122,3,85)
INTO SC VALUES (123,1,80)
INTO SC VALUES (123,2,88)
INTO SC VALUES (123,3,40)
INTO SC VALUES (123,4,NULL)
SELECT 1 FROM DUAL;

-- 测试
SELECT * from S;
SELECT * from C;
SELECT * from SC;
