DROP VIEW ZHANG;
DROP VIEW FEMALE;
DROP VIEW MATH;
-- 1．	建立张姓学生的视图，属性包括学号、姓名、选修课程名和成绩。
CREATE VIEW ZHANG AS
SELECT S.SNO,SNAME,CNAME,GRADE
FROM S
JOIN SC ON S.SNO=SC.SNO
JOIN C ON C.CNO=SC.CNO
WHERE SNAME LIKE '张%';

-- 查看ZHANG视图
SELECT * FROM ZHANG;

-- 2．	在女学生视图中查询平均成绩大于80分的学生学号与姓名。

-- 创建女学生视图
CREATE VIEW FEMALE AS
SELECT *
FROM S 
NATURAL JOIN SC
NATURAL JOIN C
WHERE SGENDER = 'F';

-- 查看FEMALE视图
SELECT * FROM FEMALE;

-- 查询平均成绩大于80分的学生学号与姓名
SELECT SNO,SNAME
FROM FEMALE
GROUP BY SNO,SNAME
HAVING 80<AVG(GRADE);


-- 3．	创建数学系MATH的学生视图，并对其进行增删改查操作（要求只能操作MATH系数据）。

-- 创建数学系MATH的学生视图
CREATE VIEW MATH AS
SELECT *
FROM S
WHERE SDEPT = 'MATH';

-- 查看MATH视图
SELECT * FROM MATH;

-- 增
INSERT INTO MATH(SNO,SNAME,SGENDER,SAGE,SDEPT) 
VALUES(211,'赫敏','F',13,'MATH');
INSERT INTO MATH(SNO,SNAME,SGENDER,SAGE,SDEPT) 
VALUES(212,'罗恩','M',13,'MATH');

-- 删
DELETE FROM MATH WHERE SNAME='罗恩';

-- 改
UPDATE MATH
SET SAGE=SAGE+1
WHERE SNAME='赫敏';

--查
SELECT * FROM MATH WHERE sno=211;


DELETE FROM MATH WHERE SNAME='赫敏';

-- 测试语句------------------------------------------------
SELECT * from S;
SELECT * from C;
SELECT * from SC;
